name: Check Performance Layers

on:
  push:
  pull_request:

jobs:
  build:
    name: Check (${{ matrix.config }}, ${{ matrix.compiler }}, ${{ matrix.generator }})
    runs-on: ${{ matrix.host-os }}
    strategy:
      fail-fast: false
      matrix:
        host-os:    ["ubuntu-latest"]
        config:     [Debug, Release]
        compiler:   [clang, gcc]
        generator:  ["Ninja", "Unix Makefiles"]
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git fetch origin +${GITHUB_SHA}:${GITHUB_REF} --update-head-ok
          git checkout ${GITHUB_SHA}
          git submodule update --init
      - name: Build and Test with Docker
        run: docker build . --file docker/build.Dockerfile
                            --build-arg CONFIG="${{ matrix.config }}"
                            --build-arg COMPILER="${{ matrix.compiler }}"
                            --build-arg GENERATOR="${{ matrix.generator }}"
