name: Check Performance Layers

on:
  push:
  pull_request:

jobs:
  build:
    name: Check (${{ matrix.config }}, ${{ matrix.compiler }}, ${{ matrix.generator }})
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        config:     [Debug, Release]
        compiler:   [clang]
        generator:  ["Ninja"]
        include:
        - config: Release
          compiler: gcc
          generator: "Ninja"
        - config: Debug
          compiler: gcc
          generator: "Unix Makefiles"
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git fetch origin +${GITHUB_SHA}:${GITHUB_REF} --update-head-ok
          git checkout ${GITHUB_SHA}
          git submodule update --init
      - name: Build and Test with Docker
        run: docker build . --file docker/build.Dockerfile
                            --build-arg CONFIG="${{ matrix.config }}"
                            --build-arg COMPILER="${{ matrix.compiler }}"
                            --build-arg GENERATOR="${{ matrix.generator }}"
